### ISSUE TITLE
Suggestion: On Writing Well by William Zinsser

### ISSUE THREAD

**Issue by bsima** [joshuacc/prose-for-programmers#12]
As a writer-turned-programmer (actually, a philosophy major, but that's certainly a lot of writing and grammer) I definitely know the value of clear writing. [On Writing Well](https://www.goodreads.com/book/show/53343.On_Writing_Well) is probably the book that taught me how to think like a good writer, in addition how to write well. It's readable prose, not a instruction book like Strunk and White. If you haven't read it, I highly suggest it. If you have, then I would suggest adding it to your references at the end.

Also, this is a very cool project, and much needed :smile:

**Comment by joshuacc** [comment]
Thanks for the kind words @bsima.

I've added _On Writing Well_ to the resources section, and hope to read it myself sometime in the near future.
