### ISSUE TITLE
Timeframe

### ISSUE THREAD

**Issue by zv** [joshuacc/prose-for-programmers#3]
@joshuacc   This is brilliant, thank you very much for embarking on this project. I have always wanted a guide intended for an audience of documentation and conceptual technical writers.

When do you anticipate this project having some material beyond the motivation document (`Why?`)?

**Comment by joshuacc** [comment]
@zv Glad that you like the idea.

I'd estimate that I'll finish up the first draft of the "Why?" chapter within the next week, and should start having chunks of the next chapter available shortly thereafter. That's subject to the demands of work and my family, though. :smile:
